# Generated by Django 3.0.7 on 2020-07-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
    ]
